### ISSUE TITLE
Matrix signal molecule - target gene with p-values

### ISSUE THREAD

**Issue by rvinas** [data2intelligence/ridge_significance#2]
Hello, congratulations on the great paper! I was wondering if you could provide a matrix where:
- Rows are signal molecules.
- Columns are target genes.
- Entries are p-values computed on the differential expression.

Would this be possible? Many thanks!

**Comment by data2intelligence** [comment]
Hi, Rvinas, do you mean a statistical significance matrix for the cytokine logFC matrix? (i.e., p-value version of the matrix in Tres package). I did not include this because p-values are not directly comparable across cytokines. Each cytokine signal has a very different number of datasets, and p-value significance is dominated by dataset count, but not entirely the true regulation significance.

If you do need such a matrix, please download the original raw data here: https://cytosig.ccr.cancer.gov/download/. Then, you can run a Wilcoxon signed-rank test to get the value by yourself.
